### ISSUE TITLE
object is not subscriptable

### ISSUE THREAD

**Issue by CrazyCreative** [twilsonco/TransmissionBot#2]
Hello 
After a clean Install I get the following error with Python3 and Python3.8.
Any help please is appreciated 
Thank you

Xxxx@Xxxx-pc:~$ python3.8 TransmissionBot/bot.py
Traceback (most recent call last):
  File "TransmissionBot/bot.py", line 801, in <module>
    def prepare_notifications(changedTransfers, states=CONFIG['notification_states']['in_channel']):
TypeError: 'NoneType' object is not subscriptable

**Comment by twilsonco** [comment]
Hey, try the current version and see if it helps. I upped the logging, so if there's other problems you can post logs (from the `transmissionbot.log` file.
_Edit: be sure to go though the definition of `CONFIG` and set the necessary values_

**Comment by CrazyCreative** [comment]
Hello and thank you for your help,
I tried the new version and now I get the following error : 

File "bot.py", line 1158, in
async def CommandPrecheck(message, whitelist=CONFIG['whitelist_user_ids']):
TypeError: 'NoneType' object is not subscriptable

My transmissionbot.log are all empty

Can you please state what line of CONFIG are required (not optionnal) 
my config for whitelist_user_ids:
"whitelist_user_ids" : ["Slimo"]
I tried
"whitelist_user_ids" : ['Slimo']

**Comment by twilsonco** [comment]
Ah, yes. See the Configuration section of the readme. Discord ids are different. Fix that and give it another go. If it's still giving you issues let me know.

In the meantime I'll add checks to make sure that config values with user/channel ids are valid when provided.

**Comment by CrazyCreative** [comment]
Thank you for your reactivity. 
I typed the ID and not the name this time.
I tried many times but nothing seems to change. I replaced the [ ] with quotes nothing changed.

**Comment by twilsonco** [comment]
OK, it's now setup so the user has to conifgure a `config.json` file themself instead of setting the `CONFIG` variable in the python file. Update the python file and download the `config-sample.json` file. Configure and save it as `config.json` and then it should work. Also make sure you're able to connect to your Transmission remote interface via Chrome or some other browser.

**Comment by CrazyCreative** [comment]
IT WORKS ! 
Thanks
