### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by jpdsc** [twilsonco/TransmissionBot#3]
Hi there,

Any chance this will get support to run with Docker? Looking at the setup steps I came to the conclusion these aren't very Docker / Dockerfile friendly as bot.py needs to be altered before (for logs) and after (for conf).

Thank you.

**Comment by twilsonco** [comment]
It wouldn't be hard. Just need to point the container to the config file and a place to store transfer data for the notification system. 

That said, I won't be adding Docker support anytime soon, just because I have it running on a Mac server and Docker essentially runs a Linux VM on Mac with much overhead, so I try to run everything natively. I'll leave this open in case someone else wants to do it. 

Sorry.

**Comment by jpdsc** [comment]
@twilsonco I am working on a Dockerfile, however. Can you explain which definition needs to be changed?
```
Configure CONFIG in bot.py to your liking
Run bot python3 /path/to/bot.py
Bot will create config.json, after which you can remove or comment the definition of CONFIG in bot.py to make future updates easier
```

I have changed
https://github.com/twilsonco/TransmissionBot/blob/ab5ac15006dde6ff183f64bac7818d2d0a329cc2/bot.py#L41
to `CONFIG = 'config.json'`, however, when starting the container I get error:

```
Traceback (most recent call last):
File "./bot.py", line 180, in <module>
CONFIG = load_json(CONFIG_JSON) if exists(CONFIG_JSON) else None # will be read from CONFIG_JSON
File "./bot.py", line 174, in load_json
jsonContents = load(open(path))
File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
return loads(fp.read(),
File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 3 column 5 (char 121)
```

The config is available
```
Dockerfile
LICENSE
README.md
UPDATES.md
bot.py
config-sample.json
config.json
example image collage.png
requirements.txt
```
Checked the permissions of config.json:
`-rwxrwxrwx 1 root root 4471 Feb 19 11:32 config.json`

Any clue?

**Comment by jpdsc** [comment]
Resolved.

**Comment by jpdsc** [comment]
@twilsonco 

The first part of the Dockerfile is done. I can now run it privately using the fork.
The only issue pending is that I cannot seem to get the notifications working. I am not sure if this is due to the torrent being in seeding complete status?
The logs also don't show any ERROR except:

`2021-02-19 19:01:29,975 [    MainThread:  bot.py:  922 -   loop_notifications()]    ERROR: Exception thrown in run_notifications: '>' not supported between instances of 'list' and 'int'`

Which I think has nothing to do with the issue that notifications aren't working.

**Comment by twilsonco** [comment]
Set the logging level to `DEBUG` and run it again. *Should* be easy to find the problem.

**Comment by jpdsc** [comment]
> Set the logging level to `DEBUG` and run it again. *Should* be easy to find the problem.

By default it's already `logger.setLevel(logging.DEBUG)`
Also, in the documentation: 

> Pick a location for the logfile on line 124; default is the same directory where bot.py resides

 seems to be outdated.

**Comment by moltheorygroup** [comment]
I see. The notification system uses a json of transfer data to work whose location is determined on line 206 of bot.py. This needs to be a persistent location for the notification system to (properly) work across restarts. Though it should still work so long as the location is writable, so I wouldn’t expect that to be the problem.

Can you post the full log output (minus any sensitive info)?

**Comment by twilsonco** [comment]
I see. The notification system uses a json of transfer data to work whose location is determined on line 206 of bot.py. This needs to be a persistent location for the notification system to (properly) work across restarts. Though it should still work so long as the location is writable, so I wouldn’t expect that to be the problem.

Can you post the full log output (minus any sensitive info)?

**Comment by jpdsc** [comment]
[transmission.log](https://github.com/twilsonco/TransmissionBot/files/6012618/transmission.log)

**Edit: on transmission.log.1**
`2021-02-19 19:59:56,050 PyNaCl is not installed, voice will NOT be supported`
But I don't think this is causing an issue

Here you go. Only thing I see is the same
`[ MainThread: bot.py: 922 - loop_notifications()] ERROR: Exception thrown in run_notifications: '>' not supported between instances of 'list' and 'int'`

I can also confirm that the file is being created. The only thing I had Dockerfile change was line 41 from `CONFIG = None` to `CONFIG = 'config.json'`

**Comment by twilsonco** [comment]
Can you check that `notification_channel_id` _is a number in your config file_, not a string or a list of numbers or strings?

**Comment by jpdsc** [comment]
> Can you check that `notification_channel_id` _is a number in your config file_, not a string or a list of numbers or strings?

Only numbers, no [ ].
I actually noticed something else. If I type t/l, it shows the current download but the ID is 11... Nothing else is downloading and all other have been finished already.
Could this have something to do with it? 

Edit, ok so I found out there was a space after the ID and this resolved it. I put the freq to 60 seconds just to test a small file and it worked.

Also saw that the completed notification shows 2 bells, it supposed to do that on a notification?

**Comment by twilsonco** [comment]
No, the id number is a per-session thing. Restarting Transmission resets it.

Could you also check that `reaction_wait_timeout` is an integer?

**Comment by jpdsc** [comment]
`"reaction_wait_timeout": 7200,` is default from config.json, I didn't change it.

Also, I have the Dockerfile together with the docker-compose.yaml template completed, will do a pull request to you tomorrow together with the updated README including instructions.

It uses COPY instead of pulling from github to ensure it also works if cloned again by someone else.
I used python:3.8-alpine only installing needed APK

Didn't have enough time to look into the log location and ended up just leaving it as it in the CONFIG_DIR.

**Comment by jpdsc** [comment]
Pull request done

**Comment by thomasdelorge** [comment]
Hi,
I saw pull request #4 was closed without merge and your image isn't foundable on docker hub ('jpdsc/transmissionbot') so i just fork it and publish it under ''tdelorge/transmissionbotdiscord"

@jpdsc : I used your pull request #4 cause it's work fine ! 💯 
@twilsonco : do you want a pull request or we leave it as a fork ?

Thanks both of you for your work 👍
